# src/streamlit/ui/pages/generate_manual_workflows/workflow_creators/topsurveys_workflow.py
"""
TopSurveys Workflow Creator  v1.0.0
=====================================
Builds a single continuous-loop Automa JSON workflow that:
  1. Opens the survey URL
  2. Loops over every page answering ALL inputs (screener + full survey)
  3. Detects disqualification phrases and exits cleanly
  4. Detects survey completion and marks success

The answers pre-generated by Gemini (stored in the DB) are baked into the
workflow as a JS lookup table so Automa can answer known questions without
calling any API at runtime. Unknown questions (post-screener body) are
handled by a generic mid-option fallback.
"""

import json
import logging
import time
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Import base class — try real path first, then the orchestrator pre-load
# names, then fall back to a local shim so the file always loads cleanly.
# ---------------------------------------------------------------------------
_BaseClass = None
for _import_name in (
    "extraction.base_workflow_creator",
    "genmw.base_workflow_creator",
):
    try:
        import importlib as _il
        _mod = _il.import_module(_import_name)
        _BaseClass = getattr(_mod, "BaseWorkflowCreator")
        break
    except Exception:
        pass

if _BaseClass is None:
    # Minimal shim — all real logic is in this file anyway
    class _BaseClass:  # type: ignore
        def __init__(self, db_manager=None):
            self.db_manager = db_manager

        def get_site_info(self) -> Dict[str, Any]:
            return {}

        def parse_persona(self, prompt):
            return prompt or {}

        def best_answer(self, question, persona):
            return None

        def b_dq_check(self):
            return None

        def b_completion_check(self):
            return None

        def b_click_next(self):
            return None

        @staticmethod
        def connect_by_id(blocks, from_id, to_id, port="output-1"):
            for b in blocks:
                if b["id"] == from_id:
                    b.setdefault("outputs", {}).setdefault(port, {"connections": []})
                    b["outputs"][port]["connections"].append(
                        {"node": to_id, "output": "output-1"}
                    )

        def assemble_workflow(self, name, description, blocks, **kw):
            return {
                "name": name, "description": description,
                "drawflow": {"nodes": {b["id"]: b for b in blocks}},
                "settings": {"blockDelay": 500, "tabLoadTimeout": 30000,
                             "onError": "keep-running"},
                "globalData": "{}",
            }

BaseWorkflowCreator = _BaseClass


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _bid() -> str:
    """Short unique block ID."""
    return uuid.uuid4().hex[:8]


def _mid_option(options) -> Optional[str]:
    if not options:
        return None
    if isinstance(options, str):
        try:
            options = json.loads(options)
        except Exception:
            return None
    return str(options[len(options) // 2]) if options else None


def _make_block(name: str, label: str, data: dict,
                dual_output: bool = False) -> dict:
    """Create a standard Automa block dict."""
    outputs = {"output-1": {"connections": []}}
    if dual_output:
        outputs["output-2"] = {"connections": []}
    return {"id": _bid(), "name": name, "label": label,
            "data": data, "outputs": outputs}


def _connect(blocks: List[dict], from_id: str, to_id: str,
             port: str = "output-1") -> None:
    for b in blocks:
        if b["id"] == from_id:
            b["outputs"][port]["connections"].append(
                {"node": to_id, "output": "output-1"}
            )
            return


# ---------------------------------------------------------------------------
# The workflow creator
# ---------------------------------------------------------------------------

class TopSurveysWorkflowCreator(BaseWorkflowCreator):

    def __init__(self, db_manager=None):
        super().__init__(db_manager)
        self._info = {
            "site_name":     "Top Surveys",
            "template_name": "Continuous Loop Engine",
            "version":       "1.0.0",
            "description":   "Screener + full survey in one unbroken workflow",
        }

    def get_site_info(self) -> Dict[str, Any]:
        return self._info

    # ------------------------------------------------------------------
    # Persona parsing (delegates to base, adds TopSurveys specifics)
    # ------------------------------------------------------------------

    def parse_persona(self, prompt: Dict[str, Any]) -> Dict[str, Any]:
        try:
            return super().parse_persona(prompt)
        except Exception:
            persona = {}
            for f in ("age","gender","city","country","education_level","job_status",
                      "industry","income_range","marital_status","household_size",
                      "has_children","username","email"):
                if prompt.get(f) is not None:
                    persona[f] = prompt[f]
            persona["_raw_content"] = prompt.get("content", "")
            return persona

    # ------------------------------------------------------------------
    # Rule-based best_answer fallback
    # ------------------------------------------------------------------

    def best_answer(self, question: Dict[str, Any],
                    persona: Dict[str, Any]) -> Optional[str]:
        try:
            result = super().best_answer(question, persona)
            if result:
                return result
        except Exception:
            pass

        q_type = (question.get("question_type") or "").lower()
        q_text = (question.get("question_text") or "").lower()
        options = question.get("options") or []
        if isinstance(options, str):
            try:
                options = json.loads(options)
            except Exception:
                options = []
        if not options:
            return None

        def find(*keywords):
            for opt in options:
                if any(k in str(opt).lower() for k in keywords):
                    return str(opt)
            return None

        if "age" in q_text and persona.get("age"):
            age = int(persona["age"])
            for opt in options:
                parts = str(opt).replace("–", "-").split("-")
                if len(parts) == 2:
                    try:
                        lo, hi = int(parts[0].strip()), int(parts[1].strip())
                        if lo <= age <= hi:
                            return str(opt)
                    except ValueError:
                        pass

        if "gender" in q_text and persona.get("gender"):
            r = find(persona["gender"].lower())
            if r: return r

        if any(w in q_text for w in ("employ","job","work","occupation")):
            if persona.get("job_status"):
                r = find(persona["job_status"].lower())
                if r: return r

        if any(w in q_text for w in ("education","degree","school")):
            if persona.get("education_level"):
                r = find(persona["education_level"].lower())
                if r: return r

        if "children" in q_text:
            has = persona.get("has_children")
            if has is True:  return find("yes")
            if has is False: return find("no")

        if q_type == "yes_no":
            return find("yes") or str(options[0])

        return _mid_option(options)

    # ------------------------------------------------------------------
    # Load Gemini-generated answers from DB
    # ------------------------------------------------------------------

    def _load_db_answers(
        self, question_ids: List[int], account_id: int
    ) -> Dict[int, str]:
        if not self.db_manager or not question_ids:
            return {}
        try:
            placeholders = ",".join(["%s"] * len(question_ids))
            rows = self.db_manager.execute_query(
                f"""
                SELECT DISTINCT ON (question_id)
                    question_id, answer_text
                FROM answers
                WHERE question_id IN ({placeholders})
                  AND account_id = %s
                  AND answer_text IS NOT NULL
                ORDER BY question_id, submitted_at DESC
                """,
                question_ids + [account_id],
                fetch=True,
            )
            result: Dict[int, str] = {}
            for row in (rows or []):
                if hasattr(row, "keys"):
                    result[row["question_id"]] = row["answer_text"]
                else:
                    result[row[0]] = row[1]
            return result
        except Exception as exc:
            logger.error(f"_load_db_answers: {exc}")
            return {}

    # ------------------------------------------------------------------
    # Persist to DB (uses correct schema — no batch_id column)
    # ------------------------------------------------------------------

    def _save_workflow(
        self,
        account_id: int,
        site_id: int,
        workflow_name: str,
        workflow_data: Dict,
        question_id: Optional[int],
    ) -> Optional[int]:
        if not self.db_manager:
            return None
        try:
            rows = self.db_manager.execute_query(
                """
                INSERT INTO workflows
                    (account_id, site_id, workflow_name, workflow_data,
                     question_id, is_active, uploaded_to_chrome)
                VALUES (%s, %s, %s, %s::jsonb, %s, TRUE, FALSE)
                RETURNING workflow_id
                """,
                (
                    account_id, site_id, workflow_name,
                    json.dumps(workflow_data), question_id,
                ),
                fetch=True,
            )
            if rows:
                row = rows[0]
                return row["workflow_id"] if hasattr(row, "keys") else row[0]
        except Exception as exc:
            logger.error(f"_save_workflow: {exc}")
        return None

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def create_workflows(
        self,
        account_id: int,
        site_id: int,
        questions: List[Dict[str, Any]],
        prompt: Dict[str, Any],
        workflow_count: int = 1,
        survey_url: str = "",
        include_click_elements: bool = True,
        include_input_elements: bool = True,
        **kwargs,
    ) -> Dict[str, Any]:
        t0 = time.time()

        persona = self.parse_persona(prompt)

        # Load Gemini answers from DB
        q_ids      = [q["question_id"] for q in questions]
        db_answers = self._load_db_answers(q_ids, account_id)

        # Build answer map: normalised question text → answer string
        answer_map: Dict[str, str] = {}
        for q in questions:
            key = q["question_text"].strip().lower()

            if q["question_id"] in db_answers:
                answer_map[key] = db_answers[q["question_id"]]
            else:
                rule = self.best_answer(q, persona)
                if rule:
                    answer_map[key] = rule
                else:
                    mid = _mid_option(q.get("options"))
                    if mid:
                        answer_map[key] = mid

        workflows_out = []
        inserted = 0

        for i in range(workflow_count):
            wf_name = (
                f"TopSurveys_{persona.get('username', 'user')}"
                f"_{i+1}_{uuid.uuid4().hex[:6]}"
            )

            wf_json = self._build_workflow(
                workflow_name=wf_name,
                survey_url=survey_url,
                questions=questions,
                answer_map=answer_map,
                include_click=include_click_elements,
                include_input=include_input_elements,
            )

            wf_id = self._save_workflow(
                account_id=account_id,
                site_id=site_id,
                workflow_name=wf_name,
                workflow_data=wf_json,
                question_id=questions[0]["question_id"] if questions else None,
            )
            if wf_id:
                inserted += 1

            workflows_out.append({
                "workflow_name":  wf_name,
                "workflow_id":    wf_id,
                "workflow_data":  wf_json,
                "batch_size":     len(questions),
                "question_text":  questions[0]["question_text"] if questions else "",
                "answers_baked":  len(answer_map),
            })

        return {
            "success":           True,
            "workflows_created": len(workflows_out),
            "workflows":         workflows_out,
            "inserted":          inserted,
            "batch_id":          f"wf_{uuid.uuid4().hex[:12]}",
            "execution_time_seconds": round(time.time() - t0, 2),
        }

    # ------------------------------------------------------------------
    # Automa JSON builder
    # ------------------------------------------------------------------

    def _build_workflow(
        self,
        workflow_name: str,
        survey_url: str,
        questions: List[Dict[str, Any]],
        answer_map: Dict[str, str],
        include_click: bool = True,
        include_input: bool = True,
    ) -> Dict[str, Any]:
        """
        Build a complete Automa workflow with:
          new-tab → wait → [DQ check → done check → per-question blocks
          → JS fallback → pause → click-next → wait] loop → close-tab
        """
        blocks: List[dict] = []

        # ── 1. Open URL ─────────────────────────────────────────────────
        open_id = _bid()
        blocks.append(_make_block("new-tab", "Open survey", {
            "url":           survey_url or "about:blank",
            "active":        True,
            "updatePrevTab": False,
        }))
        blocks[-1]["id"] = open_id

        # ── 2. Wait for page ────────────────────────────────────────────
        wait1_id = _bid()
        blocks.append(_make_block("delay", "Wait page load", {"time": 2500}))
        blocks[-1]["id"] = wait1_id

        # ── 3. DQ check (dual output) ───────────────────────────────────
        dq_id = _bid()
        dq_js = (
            "const body = (document.body.innerText || '').toLowerCase();\n"
            "const dq = ['not eligible',\"don't qualify\",'not a match',"
            "'screened out','unfortunately','disqualified','quota full','survey is full'];\n"
            "return dq.some(p => body.includes(p));"
        )
        blocks.append(_make_block("javascript-code", "DQ check",
                                  {"code": dq_js, "everyNewTab": False},
                                  dual_output=True))
        blocks[-1]["id"] = dq_id

        # ── 4. Completion check (dual output) ───────────────────────────
        done_id = _bid()
        done_js = (
            "const body = (document.body.innerText || '').toLowerCase();\n"
            "const done = ['thank you','survey complete','you have completed',"
            "'submission received','rewards credited','points added',"
            "'congratulations','well done'];\n"
            "return done.some(p => body.includes(p));"
        )
        blocks.append(_make_block("javascript-code", "Completion check",
                                  {"code": done_js, "everyNewTab": False},
                                  dual_output=True))
        blocks[-1]["id"] = done_id

        # ── 5. Per-question answer blocks ───────────────────────────────
        answer_ids: List[str] = []
        for q in questions:
            q_text   = q.get("question_text", "").strip()
            q_type   = (q.get("question_type") or "text").lower()
            answer   = answer_map.get(q_text.lower(), "")
            options  = q.get("options") or []
            if isinstance(options, str):
                try:    options = json.loads(options)
                except: options = []

            click_el = q.get("click_element") if include_click else None
            input_el = q.get("input_element") if include_input else None

            if not answer:
                answer = _mid_option(options) or "Yes"

            if q_type in ("multiple_choice", "radio", "checkbox", "dropdown", "yes_no"):
                bid = _bid()
                selector = (
                    click_el
                    or f"label"   # Automa will use :has-text via description
                )
                # Use JS click for reliability — label text matching
                click_js = (
                    f"const want = {json.dumps(answer.lower())};\n"
                    "for (const lbl of document.querySelectorAll('label, [role=\"option\"]')) {\n"
                    "  if ((lbl.innerText||'').trim().toLowerCase() === want) {\n"
                    "    lbl.click(); return true;\n"
                    "  }\n"
                    "}\n"
                    "// partial match\n"
                    "for (const lbl of document.querySelectorAll('label')) {\n"
                    "  if ((lbl.innerText||'').toLowerCase().includes(want)) {\n"
                    "    lbl.click(); return true;\n"
                    "  }\n"
                    "}\n"
                    "return false;"
                )
                blocks.append(_make_block(
                    "javascript-code",
                    f"Answer: {q_text[:50]}",
                    {"code": click_js, "everyNewTab": False,
                     "description": f"Click '{answer}' for: {q_text[:60]}"},
                ))
                blocks[-1]["id"] = bid
                answer_ids.append(bid)

            elif q_type in ("text", "textarea"):
                bid = _bid()
                fill_js = (
                    f"const ans = {json.dumps(answer)};\n"
                    f"const sel = {json.dumps(input_el or 'textarea, input[type=\\'text\\']')};\n"
                    "const el = document.querySelector(sel);\n"
                    "if (!el) return false;\n"
                    "el.focus(); el.value = ans;\n"
                    "el.dispatchEvent(new Event('input',{bubbles:true}));\n"
                    "el.dispatchEvent(new Event('change',{bubbles:true}));\n"
                    "return true;"
                )
                blocks.append(_make_block(
                    "javascript-code",
                    f"Fill: {q_text[:50]}",
                    {"code": fill_js, "everyNewTab": False},
                ))
                blocks[-1]["id"] = bid
                answer_ids.append(bid)

            elif q_type == "rating":
                bid = _bid()
                rate_js = (
                    f"const want = {json.dumps(str(answer))};\n"
                    "const candidates = Array.from(document.querySelectorAll(\n"
                    "  \"input[type='radio'],[role='radio'],[class*='rating'] input\"\n"
                    ")).filter(el => { const r=el.getBoundingClientRect(); return r.width>0&&r.height>0; });\n"
                    "if (!candidates.length) return false;\n"
                    "const match = candidates.find(el => (el.value||el.getAttribute('aria-label')||'')=== want);\n"
                    "const pick = match || candidates[Math.floor(candidates.length/2)];\n"
                    "pick.click(); pick.dispatchEvent(new Event('change',{bubbles:true}));\n"
                    "return true;"
                )
                blocks.append(_make_block(
                    "javascript-code",
                    f"Rate: {q_text[:50]}",
                    {"code": rate_js, "everyNewTab": False},
                ))
                blocks[-1]["id"] = bid
                answer_ids.append(bid)

        # ── 6. Generic JS fallback ──────────────────────────────────────
        fallback_id = _bid()
        answer_js_obj = json.dumps(answer_map, ensure_ascii=False)
        fallback_js = f"""
const ANSWERS = {answer_js_obj};

function closestLabel(el) {{
  let node = el;
  for (let i = 0; i < 6; i++) {{
    const h = node.querySelector && node.querySelector('h1,h2,h3,h4,h5,legend,p,[role="heading"]');
    if (h && h.innerText && h.innerText.trim().length > 4)
      return h.innerText.trim().toLowerCase();
    node = node.parentElement;
    if (!node) break;
  }}
  return '';
}}

function clickAnswer(container, answer) {{
  const labels = Array.from(container.querySelectorAll('label,[role="radio"],[role="checkbox"],[role="option"]'));
  const exact  = labels.find(l => (l.innerText||'').trim().toLowerCase() === answer.toLowerCase());
  if (exact) {{ exact.click(); return true; }}
  const partial = labels.find(l => (l.innerText||'').toLowerCase().includes(answer.toLowerCase()));
  if (partial) {{ partial.click(); return true; }}
  if (labels.length) {{ labels[Math.floor(labels.length/2)].click(); return true; }}
  return false;
}}

let answered = 0;

// Handle radio/checkbox groups
document.querySelectorAll('fieldset,[role="group"],form>div,form>section').forEach(c => {{
  const rect = c.getBoundingClientRect();
  if (rect.width < 10 || rect.height < 10) return;
  const radios = c.querySelectorAll("input[type='radio']:not(:checked)");
  const checks = c.querySelectorAll("input[type='checkbox']:not(:checked)");
  if (!radios.length && !checks.length) return;
  const qText = closestLabel(c);
  const entry = Object.entries(ANSWERS).find(([k]) => qText && qText.includes(k));
  if (entry) {{
    if (clickAnswer(c, entry[1])) answered++;
  }} else {{
    const inputs = Array.from(radios.length ? radios : checks);
    const mid = inputs[Math.floor(inputs.length/2)];
    const lbl = document.querySelector(`label[for='${{mid.id}}']`) || mid.closest('label');
    if (lbl) lbl.click(); else mid.click();
    answered++;
  }}
}});

// Handle text inputs
document.querySelectorAll("textarea,input[type='text']").forEach(inp => {{
  const rect = inp.getBoundingClientRect();
  if (rect.width < 10 || rect.height < 10) return;
  if (inp.value && inp.value.trim()) return;
  const qText = closestLabel(inp);
  const entry = Object.entries(ANSWERS).find(([k]) => qText && qText.includes(k));
  inp.value = entry ? entry[1] : 'Not applicable';
  inp.dispatchEvent(new Event('input',{{bubbles:true}}));
  inp.dispatchEvent(new Event('change',{{bubbles:true}}));
  answered++;
}});

return answered;
""".strip()

        blocks.append(_make_block(
            "javascript-code",
            "Fallback: answer remaining inputs",
            {"code": fallback_js, "everyNewTab": False,
             "description": "Handles any inputs not matched by per-question blocks"},
        ))
        blocks[-1]["id"] = fallback_id

        # ── 7. Pause after answering ────────────────────────────────────
        pause_id = _bid()
        blocks.append(_make_block("delay", "Pause after answers", {"time": 900}))
        blocks[-1]["id"] = pause_id

        # ── 8. Click Next / Submit ──────────────────────────────────────
        next_id = _bid()
        next_js = (
            "const labels = ['next','continue','submit','proceed','done','finish'];\n"
            "const btns = Array.from(document.querySelectorAll(\n"
            "  \"button,input[type='submit'],[role='button']\"\n"
            ")).filter(el => { const r=el.getBoundingClientRect(); return r.width>0&&r.height>0; });\n"
            "for (const l of labels) {\n"
            "  const b = btns.find(el => (el.innerText||el.value||'').toLowerCase().trim().startsWith(l));\n"
            "  if (b) { b.click(); return 'clicked:'+l; }\n"
            "}\n"
            "if (btns.length) { btns[btns.length-1].click(); return 'clicked:last'; }\n"
            "return 'no-button-found';"
        )
        blocks.append(_make_block(
            "javascript-code", "Click Next/Submit",
            {"code": next_js, "everyNewTab": False},
        ))
        blocks[-1]["id"] = next_id

        # ── 9. Wait for next page ───────────────────────────────────────
        wait2_id = _bid()
        blocks.append(_make_block("delay", "Wait next page", {"time": 2200}))
        blocks[-1]["id"] = wait2_id

        # ── 10. Close tab ───────────────────────────────────────────────
        close_id = _bid()
        blocks.append(_make_block("close-tab", "Close tab",
                                  {"description": "Survey done or DQ"}))
        blocks[-1]["id"] = close_id

        # ── Wire connections ────────────────────────────────────────────
        _connect(blocks, open_id,   wait1_id)
        _connect(blocks, wait1_id,  dq_id)

        # DQ: true(output-1) → close, false(output-2) → done check
        _connect(blocks, dq_id,   close_id,  port="output-1")
        _connect(blocks, dq_id,   done_id,   port="output-2")

        # Done: true → close, false → first answer block (or fallback)
        _connect(blocks, done_id, close_id,  port="output-1")

        first_answer = answer_ids[0] if answer_ids else fallback_id
        _connect(blocks, done_id, first_answer, port="output-2")

        # Chain per-question answer blocks
        for idx in range(len(answer_ids) - 1):
            _connect(blocks, answer_ids[idx], answer_ids[idx + 1])
        if answer_ids:
            _connect(blocks, answer_ids[-1], fallback_id)

        # Fallback → pause → next → wait → loop back to DQ check
        _connect(blocks, fallback_id, pause_id)
        _connect(blocks, pause_id,    next_id)
        _connect(blocks, next_id,     wait2_id)
        _connect(blocks, wait2_id,    dq_id)   # ← the loop

        # ── Assemble final workflow object ──────────────────────────────
        return {
            "name":        workflow_name,
            "icon":        "riIcons:survey-line",
            "color":       "#2563eb",
            "description": (
                "Continuous loop: screener + full survey in one run. "
                "Pre-loaded with Gemini answers; falls back to mid-option "
                "for unknown questions. Stops on DQ or completion."
            ),
            "drawflow": {
                "nodes": {b["id"]: b for b in blocks}
            },
            "settings": {
                "blockDelay":         500,
                "tabLoadTimeout":     30000,
                "onError":            "keep-running",
                "executedBlockOnWeb": False,
                "publicId":           "",
                "restartTimes":       0,
                "notification":       False,
                "reuseLastState":     False,
            },
            "globalData": json.dumps({
                "survey_url":    survey_url,
                "answers_count": len(answer_map),
                "generated_at":  datetime.now().isoformat(),
            }),
            "version": "1.0.0",
        }